language: python
python:
  - "2.7"

before_install:
  # This workaround is required to avoid libstdc++ errors
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-fade-all-pins
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-lib
  - PLATFORMIO_PROJECT_DIR=examples/arduino-ping-hc04
  - PLATFORMIO_PROJECT_DIR=examples/spl-blink
  - PLATFORMIO_PROJECT_DIR=examples/spl-flash
  - PLATFORMIO_PROJECT_DIR=examples/spl-uart

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

notifications:
  email: false

  slack:
    rooms:
      secure: "JirBq/um4E+UNrkheapLD7IxveySs6AYycJsCnhBdwW3jeXP7ZhHLQr5oOjZWHW/bjQ3ncGs6CrTClbBuea0zUAUtlg7mzrO3y0uomwycgy4VSiPi7ps7X7YBKuuX4Xo/NTEa2SML759hLE0rESIX37UnRAnw63OditUE7qDfJy8Lx3nK6sZUBrQ12J+PzRwlDblaz78ZbGuHMWemVChcm5koCwxNIMDvvwcZH+lyOfOm+OOHKyeS4wk6B5lEjJ/kUIkKp6YgtBtjhOkQDeidjfUCU1BcTTkI3JB+LwjQgeaacpjvIV2M8iwQJOaMiB+YlyPdnrWw18ubyLCnuzfgRu8vDulhpfuZkWz/v++1ReBAN0ju8lLnu1MPaA6LNZ+bJuC6l+nBbu1CQW/lsIjLwfh2kgNk0LkjGCRfhwsOpU/c0rA61+4OjrQbe4jscPmqU9Yku3whnJwdwEskTlD25Q1IUYq1UjE1z6LpytZ18wFcPPySTBUbWW3lmlbCbzj4gQfpTGx/rvk2zbsI52jP8vBR4VEpsJqGO2n3mlnFLrQCxslpo9F+EH0VoIVrwFsfZrH41Dx2X36i5/cI2JXSrEqeBfILvtIHuAfwxq6+g/ULZCakSqzu+eP88KU67S0ifGVW5k0lNOSsuskvbVBcsuG+q5O1BPG/qDAyWSAwwg="
    on_failure: always
    on_success: change
